down/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView
from .views import *

app_name = 'django'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', Registration.as_view(), name='signup'),
    path('change-user/', ChangeImg.as_view(), name='change-user')
]

website/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Admin(AbstractUser):
    logo = models.ImageField()
    file = models.FileField()
    file_name = models.CharField(max_length=100)

class Files(models.Model):
    pass

website/views.py
from django.shortcuts import render, reverse, redirect
from django.urls import reverse_lazy
from django.views import generic
from .models import *
from .form import *

class Home(generic.TemplateView):
    template_name = 'index.html'
    
class Registration(generic.CreateView):
    template_name = 'registration/signup.html'
    form_class = Easy
    
    def get_success_url(self):
        return reverse('django:login')

class ChangeImg(generic.UpdateView):
    form_class = Img
    template_name = "change-user.html"
    success_url = reverse_lazy("django:home")

    def get_object(self):
        return self.request.user
    
# def addfile(request):
#     if request.method == "POST":
#         form = FileSubmit(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect("/")
#     else:
#         form = FileSubmit()

#     context = {
#         "form": form,
#         "file": Admin.objects.all(),
#     }
#     return render(request, "home.html", context)

website/templates/change-user.html
{% extends 'index.html' %}
{% load static %}

{% block content %}

<div class="d-flex flex-column align-items-center text-center">

  </div>

  <style>
      body{
        background-color: white;
      }
      .changed_image{
        width: 10%;
        border-radius: 10%;
        border: 1px solid black;
      }

      .file-image{
        width: 34%;
        display: grid;
        margin-top: 20px;
        margin-left: 32%;
      }
      @media screen and (max-width: 750px) {
        .changed_image{
          width: 50%;
        }
      }
  </style>

{% endblock %}

website/templates/home.html
{% load static %}

<!-- user sign up -->

<link rel="stylesheet" href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css">
<link rel="stylesheet" href="https://unpkg.com/filepond/dist/filepond.min.css">

<!-- user login -->

{% if request.user.is_authenticated %}
<div class="container">
    <div class="main-body">
    
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    {% if request.user.logo %}
                    <img src="{{ request.user.logo.url }}" alt="Your image" class="rounded-circle" width="150px" height="150">
                    {% endif %}
                    {% if not request.user.logo %}
                    <img src="{% static 'user.png' %}" alt="Your image" class="rounded-circle" width="150" height="150">
                    {% endif %}
                    <div class="mt-3">
                      <h4>{{ request.user.username }}</h4>
                      <p class="text-secondary mb-1">Full database</p>
                      <p class="text-muted font-size-sm">Uzbekistan</p>
                      <button class="btn btn-primary">Follow</button>
                      <button class="btn btn-outline-primary">Message</button>
                    </div>
                  </div>
                </div>
              </div>

              <!-- users files -->
        

              <!-- <form class="text-center" method="post">
                {% csrf_token %}
                {{ form }}
              </form> -->
              <!-- end user files -->

            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ request.user.username }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ request.user.email }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      +998 93 212 28 18
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Mobile</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        +998 93 212 28 18
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      Uzbekistan, Andijon, Poytug
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-12">
                      <a class="btn btn-info " href="{% url 'django:change-user' %}">Edit</a>
                    </div>
                  </div>
                </div>
              </div>

            </div>
          </div>

        </div>
    </div>

<style>
    body{
    color: #1a202c;
    text-align: left;
    background-color: #e2e8f0;    
}
.main-body {
    padding: 15px;
}
.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
}

.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
}

.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}

.gutters-sm {
    margin-right: -8px;
    margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
    padding-right: 8px;
    padding-left: 8px;
}
.mb-3, .my-3 {
    margin-bottom: 1rem!important;
}

.bg-gray-300 {
    background-color: #e2e8f0;
}
.h-100 {
    height: 100%!important;
}
.shadow-none {
    box-shadow: none!important;
}


</style>
{% endif %}

{% if not request.user.is_authenticated %}
<h1 class="text-center mt-5 text-light">Plaese register our site</h1>
{% endif %}

website/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'site-icon.png' %}">
    <title>Save file</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'django:home' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'django:signup' %}">SignUp</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'django:login' %}">Login</a>
                </li>
                {% endif %}
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'django:logout' %}" tabindex="-1" aria-disabled="true">Logout</a>
                </li>
                {% endif %}
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      
    




    {% block content %}

    {% include 'home.html' %}

    {% endblock content %}



    <style>
        .helptext {
            display: none;
        }
    </style>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>